security.oauth2.client.client-id: petstore
security.oauth2.client.client-secret: petstoresecret
security.oauth2.client.authorized-grant-types: authorization_code,refresh_token,implicit,password,client_credentials
security.oauth2.client.scope: abcde
security.oauth2.client.auto-approve-scopes: abcde
security.oauth2.client.accessTokenUri: http://localhost:9999/uaa/oauth/token
security.oauth2.client.userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
security.oauth2.client.tokenInfoUri: http://localhost:9999/uaa/oauth/check_token